<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="5" total="5" passed="0">
  <reporter-output>
    <line>
      <![CDATA[fail: title is not matching]]>
    </line>
    <line>
      <![CDATA[fail: title is not matching]]>
    </line>
    <line>
      <![CDATA[fail: title is not matching]]>
    </line>
  </reporter-output>
  <suite name="Failed suite [Suite]" duration-ms="81839" started-at="2019-10-31T04:03:32Z" finished-at="2019-10-31T04:04:54Z">
    <groups>
    </groups>
    <test name="chromeTest(failed)" duration-ms="74787" started-at="2019-10-31T04:03:32Z" finished-at="2019-10-31T04:04:47Z">
      <class name="Script.create_user_script">
        <test-method status="PASS" signature="precondition(java.lang.String)[pri:0, instance:Script.create_user_script@14acaea5]" name="precondition" is-config="true" duration-ms="18260" started-at="2019-10-31T09:33:32Z" finished-at="2019-10-31T09:33:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="create_user()[pri:0, instance:Script.create_user_script@14acaea5]" name="create_user" duration-ms="12" started-at="2019-10-31T09:33:50Z" finished-at="2019-10-31T09:33:50Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException

	at Script.create_user_script.create_user(create_user_script.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_user -->
        <test-method status="PASS" signature="postcondition(org.testng.ITestResult)[pri:0, instance:Script.create_user_script@14acaea5]" name="postcondition" is-config="true" duration-ms="3078" started-at="2019-10-31T09:33:50Z" finished-at="2019-10-31T09:33:53Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=create_user status=FAILURE method=create_user_script.create_user()[pri:0, instance:Script.create_user_script@14acaea5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- Script.create_user_script -->
      <class name="Script.login_script1">
        <test-method status="PASS" signature="precondition(java.lang.String)[pri:0, instance:Script.login_script1@46d56d67]" name="precondition" is-config="true" duration-ms="27053" started-at="2019-10-31T09:33:53Z" finished-at="2019-10-31T09:34:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="login_script()[pri:0, instance:Script.login_script1@46d56d67]" name="login_script" duration-ms="21450" started-at="2019-10-31T09:34:20Z" finished-at="2019-10-31T09:34:42Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Generic.Basepage.titlewait(Basepage.java:29)
	at Script.login_script1.login_script(login_script1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[fail: title is not matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_script -->
        <test-method status="PASS" signature="postcondition(org.testng.ITestResult)[pri:0, instance:Script.login_script1@46d56d67]" name="postcondition" is-config="true" duration-ms="4912" started-at="2019-10-31T09:34:42Z" finished-at="2019-10-31T09:34:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login_script status=FAILURE method=login_script1.login_script()[pri:0, instance:Script.login_script1@46d56d67] output=fail: title is not matching]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- Script.login_script1 -->
    </test> <!-- chromeTest(failed) -->
    <test name="firefoxTest(failed)" duration-ms="81839" started-at="2019-10-31T04:03:32Z" finished-at="2019-10-31T04:04:54Z">
      <class name="Script.create_user_script">
        <test-method status="PASS" signature="precondition(java.lang.String)[pri:0, instance:Script.create_user_script@5c3bd550]" name="precondition" is-config="true" duration-ms="21548" started-at="2019-10-31T09:33:32Z" finished-at="2019-10-31T09:33:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="create_user()[pri:0, instance:Script.create_user_script@5c3bd550]" name="create_user" duration-ms="0" started-at="2019-10-31T09:33:54Z" finished-at="2019-10-31T09:33:54Z">
          <exception class="java.lang.Error">
            <message>
              <![CDATA[Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Error: Unresolved compilation problems: 
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException
	Unhandled exception type InterruptedException

	at Script.create_user_script.create_user(create_user_script.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Error -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- create_user -->
        <test-method status="PASS" signature="postcondition(org.testng.ITestResult)[pri:0, instance:Script.create_user_script@5c3bd550]" name="postcondition" is-config="true" duration-ms="3126" started-at="2019-10-31T09:33:54Z" finished-at="2019-10-31T09:33:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=create_user status=FAILURE method=create_user_script.create_user()[pri:0, instance:Script.create_user_script@5c3bd550] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- Script.create_user_script -->
      <class name="Script.logout_script">
        <test-method status="PASS" signature="precondition(java.lang.String)[pri:0, instance:Script.logout_script@604ed9f0]" name="precondition" is-config="true" duration-ms="18627" started-at="2019-10-31T09:34:32Z" finished-at="2019-10-31T09:34:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="logout_script()[pri:0, instance:Script.logout_script@604ed9f0]" name="logout_script" duration-ms="1662" started-at="2019-10-31T09:34:51Z" finished-at="2019-10-31T09:34:52Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Generic.Basepage.element_visiblity(Basepage.java:43)
	at POM.actitime_enter_timetrack.clicklogot(actitime_enter_timetrack.java:48)
	at Script.logout_script.logout_script(logout_script.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[fail: title is not matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- logout_script -->
        <test-method status="FAIL" signature="postcondition(org.testng.ITestResult)[pri:0, instance:Script.logout_script@604ed9f0]" name="postcondition" is-config="true" duration-ms="0" started-at="2019-10-31T09:34:52Z" finished-at="2019-10-31T09:34:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=logout_script status=FAILURE method=logout_script.logout_script()[pri:0, instance:Script.logout_script@604ed9f0] output=fail: title is not matching]]]>
              </value>
            </param>
          </params>
          <exception class="org.openqa.selenium.WebDriverException">
            <message>
              <![CDATA[Failed to decode response from marionette
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ADMINISTER', ip: '192.168.225.135', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191001234643, moz:geckodriverVersion: 0.25.0, moz:headless: false, moz:processID: 6236, moz:profile: C:\Users\Administere\AppDat..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 6.3, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 47410649-1cf7-41e9-8d39-624dd38f9db5]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.WebDriverException: Failed to decode response from marionette
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'
System info: host: 'ADMINISTER', ip: '192.168.225.135', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_181'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities {acceptInsecureCerts: true, browserName: firefox, browserVersion: 69.0.2, javascriptEnabled: true, moz:accessibilityChecks: false, moz:buildID: 20191001234643, moz:geckodriverVersion: 0.25.0, moz:headless: false, moz:processID: 6236, moz:profile: C:\Users\Administere\AppDat..., moz:shutdownTimeout: 60000, moz:useNonSpecCompliantPointerOrigin: false, moz:webdriverClick: true, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, platformVersion: 6.3, rotatable: false, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify}
Session ID: 47410649-1cf7-41e9-8d39-624dd38f9db5
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:609)
	at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:295)
	at Generic.Photo.getphoto(Photo.java:16)
	at Generic.BaseTest.postcondition(BaseTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:712)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.WebDriverException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- Script.logout_script -->
      <class name="Script.login_script1">
        <test-method status="PASS" signature="precondition(java.lang.String)[pri:0, instance:Script.login_script1@91161c7]" name="precondition" is-config="true" duration-ms="21086" started-at="2019-10-31T09:33:57Z" finished-at="2019-10-31T09:34:18Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- precondition -->
        <test-method status="FAIL" signature="login_script()[pri:0, instance:Script.login_script1@91161c7]" name="login_script" duration-ms="11571" started-at="2019-10-31T09:34:18Z" finished-at="2019-10-31T09:34:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.fail(Assert.java:101)
	at Generic.Basepage.titlewait(Basepage.java:29)
	at Script.login_script1.login_script(login_script1.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1129)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:400)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[fail: title is not matching]]>
            </line>
          </reporter-output>
        </test-method> <!-- login_script -->
        <test-method status="PASS" signature="postcondition(org.testng.ITestResult)[pri:0, instance:Script.login_script1@91161c7]" name="postcondition" is-config="true" duration-ms="2580" started-at="2019-10-31T09:34:29Z" finished-at="2019-10-31T09:34:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login_script status=FAILURE method=login_script1.login_script()[pri:0, instance:Script.login_script1@91161c7] output=fail: title is not matching]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postcondition -->
      </class> <!-- Script.login_script1 -->
    </test> <!-- firefoxTest(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
